baseURL = "https://n1o.github.io/"
title = "Artificial Intelligence and Machine Learning Research"

theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"

pagination.pagerSize = 20

pygmentsStyle = "b2"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true

disqusShortname = "mbarak-io"


[services]
  [services.googleAnalytics]
    ID =  "G-5WLCXX3LGJ"

[params]
    author = "Marek Barak"
    description = "Artificial Intelligence and Machine Learning Research" 
    keywords = "blog,developer,personal"
    info = "Artificial Intelligence and Machine Learning Research"
    
    footerContent = "Data and Technology"
    # katex = true
    math = true
    dateFormat = "January 2, 2006"
    # gravatar = "mrk.barak@gmail.com"
    avatarurl = "images/avatar.jpg"
    hideFooter = true
    hideCredits = false
    hideCopyright = false
    since = 2020

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    colorScheme = "auto"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = true

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []
   

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/n1o"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 3
    url = "https://twitter.com/n1o_cr0Tx"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/marek-bar%C3%A1k-31977a55/"
[[params.social]]
    name = "Medium"
    icon = "fa fa-medium"
    weight = 5
    url = "https://medium.com/@n1o_cr0Tx"
[[params.social]]
    name = "RSS"
    icon = "fa fa-rss"
    weight = 6
    url = "https://n1o.github.com"
    rel = "alternate"
    type = "application/rss+xml"


[languages]
    [languages.en]
        languageName = "English"
        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"
            
            [[languages.en.menu.main]]
            name = "Writing"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Awesome T5"
            weight = 3
            url = "awesome-t5/"

            [[languages.en.menu.main]]
            name = "Awesome SSM"
            weight = 4
            url = "awesome-ssm/"

            [[languages.en.menu.main]]
            name = "Projects"
            weight = 5
            url = "projects/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 6
            url = "contact/"
